version: '3.8'

services:
    django:
        build:
            context: django
        container_name: django_app
        # env_file:
        #     .env
        volumes:
            - static_volume:/app/static
            - media_volume:/app/media
        expose:
            - "8000"
        restart: on-failure
        networks: 
          - ft_transcendence
        # depends_on:
        #     - db

    nginx:
        image: nginx
        container_name: nginx_server
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
          - "8080:8080"
        networks: 
          - ft_transcendence
        build:
            context: nginx
        restart: on-failure
        depends_on:
          - django

volumes:
    static_volume:
    media_volume:
    postgres_data:

networks:
    ft_transcendence:
      driver: bridge
    #   name: ft_transcendence
