# Generated by Django 4.2 on 2024-07-18 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_initial'),
        ('friends', '0003_alter_friendship_unique_together'),
    ]

    operations = [
    ]
